"""
Django settings for Porsche project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ifh$zhums7$pnbf%2s)0cz9#j0n&55p#qsa#1(udt+!bfwo354'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

NUM_SESSIONS_ALLOWED=5
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'events',
    'forms',
    "user_account",
    "colorfield",
    'django_countries',
    'ckeditor',
    "widget_tweaks",
    "import_export",
    "rest_framework", 
    'channels',
    "weasyprint",
    "channels_redis",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Porsche.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Porsche.wsgi.application'

ASGI_APPLICATION = "Porsche.asgi.application" 
# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

db_evento="db.sqlite3"
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, db_evento),
    }
}


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}
# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



AUTHENTICATION_BACKENDS = [

    'user_account.auth_backend.PasswordlessAuthBackend',
    # 'user_account.utils.auth_backend.EmailAuthBackend',
    "django.contrib.auth.backends.ModelBackend",
    #login con OAUTH de redes sociales
    # "djoser.social.backends.facebook.FacebookOAuth2Override",
    # "social_core.backends.google.GoogleOAuth2",
    # "social_core.backends.steam.SteamOpenId",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]


PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')


MEDIA_URL = '/files/'
MEDIA_ROOT = os.path.join(BASE_DIR, "files")

CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"




EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = "vintaw.01@gmail.com"
EMAIL_PORT = 587

# # ejemplo de escribiendola en archivo en el server
# # EMAIL_HOST_PASSWORD =  "my_shitty_password" 
EMAIL_HOST_PASSWORD = ""

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg','pdf']

# TEST
DESTINATARIOS_ORACION=["vintaw.01@gmail.com"]
DESTINATARIOS_TE=["vintaw.01@gmail.com"]
# DESTINATARIOS_TE=["admin@glsteamedition.com","vintaw.01@gmail.com","alexis@thinkof.tech","rafaelgarcia.com@gmail.com"]



DEFAULT_FILE_STORAGE = 'Porsche.storage.ASCIIFileSystemStorage'
# AUTH_PASSWORD_VALIDATORS = []