# Generated by Django 2.2.13 on 2021-01-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_auto_20201028_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlDeploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_as_main', models.BooleanField(default=True, help_text='Si activas la casilla la pagina principal sera la pagina de landing,\n        si la desactivas, la pagina principal sera la pagina para el ingreso de usuario')),
                ('allow_register', models.BooleanField(default=False, help_text='Si activas la casilla  permitiras un boton(en la pagina de langing y de login)\n     que redirige a una pagina para que nuevos usuarios se registren, si la desactivas se impide el registro de nuevos usuarios')),
                ('allow_login', models.BooleanField(default=False, help_text='Si activas la casilla  permitiras que en la pagina de landing se habilite un boton que redirige\n    a una apgina apra que los usuarios se logueen, si la desactivas se impide el logueo de cualquier usuario ')),
            ],
        ),
    ]
