# Generated by Django 2.2.13 on 2021-02-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_controldeploy'),
    ]

    operations = [
        migrations.AddField(
            model_name='controldeploy',
            name='gtag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controldeploy',
            name='allow_login',
            field=models.BooleanField(default=False, help_text='Si activas la casilla  permitiras que en la pagina de landing se habilite un boton que redirige\n    a una pagina para que los usuarios se logueen, si la desactivas se impide el logueo de usuarios desde la landing page '),
        ),
        migrations.AlterField(
            model_name='controldeploy',
            name='allow_register',
            field=models.BooleanField(default=False, help_text='Si activas la casilla  permitiras un boton en las pagina de landing \n     que redirige a una pagina para que nuevos usuarios se registren, si la desactivas se impide el registro de nuevos usuarios desde la landing page'),
        ),
        migrations.AlterField(
            model_name='controldeploy',
            name='landing_as_main',
            field=models.BooleanField(default=True, help_text='Si activas la casilla la pagina de inicio sera la pagina de landing,\n        si la desactivas, la pagina de inicio sera la pagina para el ingreso de usuario(login)'),
        ),
    ]
