# Generated by Django 2.2.13 on 2021-02-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_auto_20210202_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='controldeploy',
            name='lobby_as_firstpage',
            field=models.BooleanField(default=False, help_text='Si activas la casilla al loguearse redirigira al lobby,\n        si la desactivas al loguearse redirigira al video principal(opcion mas comun)'),
        ),
    ]
