# Generated by Django 2.2.13 on 2021-02-10 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_controldeploy_lobby_as_firstpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='controldeploy',
            name='event_in_mainpage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='controldeploy',
            name='room_in_mainpage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.Room'),
        ),
    ]
