# Generated by Django 2.2.13 on 2021-02-11 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_auto_20210209_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_room', to='events.Room'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='show_in_lobby',
            field=models.BooleanField(default=False),
        ),
    ]
