# Generated by Django 2.2.13 on 2021-02-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_auto_20210211_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeelement',
            name='external_link_url',
            field=models.URLField(default='https://events.house', max_length=149),
        ),
        migrations.AddField(
            model_name='programmeelement',
            name='has_external_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programmeelement',
            name='link_text',
            field=models.CharField(default='Ir a la Sala', max_length=149),
        ),
    ]
