# Generated by Django 2.2.13 on 2021-03-03 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_auto_20210218_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_user',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
