# Generated by Django 2.2.13 on 2021-03-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_event_user_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='controldeploy',
            name='mess_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controldeploy',
            name='mess_error_datos_incorrectos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controldeploy',
            name='mess_exito',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controldeploy',
            name='mess_inactivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controldeploy',
            name='mess_landing_acceso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controldeploy',
            name='mess_no_registrado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
