# Generated by Django 2.2.13 on 2021-09-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_auto_20210303_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='controldeploy',
            name='free_page',
            field=models.BooleanField(default=True, help_text='Si activas la casilla la pagina sera accesible por todo publico, si la desactivas solo podran acceder\n     los previamente registrados'),
        ),
    ]
