# Generated by Django 2.2.13 on 2021-11-25 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_controldeploy_free_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerDosha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=149, unique=True)),
                ('email', models.CharField(max_length=149, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('speakerdosha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programme_element_room', to='events.SpeakerDosha')),
            ],
        ),
    ]
