# Generated by Django 2.2.13 on 2021-11-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_auto_20211125_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speakerdosha',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='question',
            name='speakerdosha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_dosha', to='events.SpeakerDosha'),
        ),
        migrations.AlterField(
            model_name='speakerdosha',
            name='email',
            field=models.CharField(blank=True, max_length=149, null=True),
        ),
    ]
