# Generated by Django 2.2.13 on 2021-11-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_auto_20211128_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speakerdosha',
            options={'verbose_name_plural': 'speakers(Dosha)'},
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=199),
        ),
    ]
