# Generated by Django 3.2 on 2021-06-07 11:09

from django.db import migrations, models
import django.utils.timezone
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_suvw_encuesta_q5_calificacion_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=149)),
                ('contenido', djrichtextfield.models.RichTextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
