# Generated by Django 3.2 on 2021-06-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_textarticles'),
    ]

    operations = [
        migrations.AddField(
            model_name='textarticles',
            name='key',
            field=models.CharField(default='identificador', max_length=149),
        ),
    ]
