# Generated by Django 3.2 on 2021-06-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_textarticles_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextArticles',
            new_name='TextArticle',
        ),
    ]
