# Generated by Django 3.2 on 2021-06-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_rename_textarticles_textarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='suvw_encuesta',
            name='q6_comentarios',
            field=models.TextField(null=True),
        ),
    ]
