# Generated by Django 2.2.13 on 2021-11-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20211127_0508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SUVW_Encuesta',
            new_name='JuntaVP_Encuesta',
        ),
    ]
