# Generated by Django 2.2.13 on 2021-11-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20211127_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juntavp_encuesta',
            name='q3_calificacion_de_duracion',
            field=models.CharField(choices=[('ML', 'Muy Larga'), ('L', 'Larga'), ('A', 'Adecuada'), ('R', 'Rápida'), ('MR', 'Muy Rápida')], default='A', max_length=3),
        ),
    ]
