# Generated by Django 2.2.13 on 2021-01-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.IntegerField(choices=[(0, 'Aguascalientes'), (1, 'Baja California'), (2, 'Baja California Sur'), (3, 'Campeche'), (4, 'Chiapas'), (5, 'Chihuahua'), (6, 'Coahuila'), (7, 'Colima'), (8, 'Distrito Federal'), (9, 'Durango'), (10, 'Guanajuato'), (11, 'Guerrero'), (12, 'Hidalgo'), (13, 'Jalisco'), (14, 'Estado de Mexico'), (15, 'Michoacan'), (16, 'Morelos'), (17, 'Nayarit'), (18, 'Nuevo Leon'), (19, 'Oaxaca'), (20, 'Puebla'), (21, 'Queretaro'), (22, 'Quintana Roo'), (23, 'San Luis Potosi'), (24, 'Sinaloa'), (25, 'Sonora'), (26, 'Tabasco'), (27, 'Tamaulipas'), (28, 'Tlaxcala'), (29, 'Veracruz'), (30, 'Yucatan'), (31, 'Zacatecas')], default=0),
        ),
    ]
